import { createApp } from 'vue'
import App from './App.vue'
import Vant from 'vant'
import 'vant/lib/index.css'
import * as VueRouter from 'vue-router'  //引入vue-router
import routes from './confg/route'
import store from "./store";

import { TUIComponents, TUICore, genTestUserSig } from './TUIKit';
// import TUICallKit
import { TUICallKit } from '@tencentcloud/call-uikit-vue';

const SDKAppID = 1400811433; // Your SDKAppID
const secretKey = 'a47d5c07b8c677f010fc32aa2c2c4b33cfd56ee43c1209424aeeba01697f05c3'; //Your secretKey
const userID = '8CTIP'; // User ID

// init TUIKit
const TUIKit = TUICore.init({
    SDKAppID,
});
// TUIKit add TUIComponents
TUIKit.use(TUIComponents);
// TUIKit add TUICallKit
TUIKit.use(TUICallKit);
// login TUIKit
// TUIKit.login({
//     userID: userID,
//     userSig: genTestUserSig({
//         SDKAppID,
//         secretKey,
//         userID,
//     }).userSig, // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
// });
export default TUIKit;
// 3. 创建路由实例并传递 `routes` 配置
// 你可以在这里输入更多的配置，但我们在这里
// 暂时保持简单

const router = VueRouter.createRouter({
    // 4. 内部提供了 history 模式的实现。为了简单起见，我们在这里使用 hash 模式。
    history: VueRouter.createWebHashHistory(),
    routes, // `routes: routes` 的缩写
})
const app = createApp(App);
app.use(TUIKit);
app.use(store);
app.use(Vant);
app.use(router);
app.mount('#app');


